apiVersion: v1
kind: Service
metadata:
  name: {{ include "shard-listener.fullname" . }}
  labels:
    {{- include "shard-listener.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "shard-listener.selectorLabels" . | nindent 4 }}
  ports:
    - name: metrics
      port: {{ .Values.service.metricsPort }}
      targetPort: metrics
      protocol: TCP
